"""initial schema

Revision ID: 03f4db502e26
Revises:
Create Date: 2026-06-09 19:29:47.550414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f4db502e26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.Enum('OIDC', 'BUILTIN', name='authprovider'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_external_id'), ['external_id'], unique=True)

    op.create_table('instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('PERSONAL', 'SHARED', name='instancetype'), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'STOPPED', 'CREATING', name='instancestatus'), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instances_cluster_id'), ['cluster_id'], unique=True)

    op.create_table('user_departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'department_id', name='uq_user_department')
    )
    with op.batch_alter_table('user_departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_departments_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_departments_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('sql_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'ERROR', 'BLOCKED', name='auditstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('client_info', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('db_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_password_enc', sa.String(length=512), nullable=False),
    sa.Column('account_type', sa.Enum('NORMAL', 'SUPER', name='accounttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'account_name', name='uq_instance_account_name'),
    sa.UniqueConstraint('instance_id', 'user_id', name='uq_instance_user_account')
    )
    with op.batch_alter_table('db_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_db_accounts_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_db_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('department_instance_bindings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=True),
    sa.Column('default_permission', sa.Enum('READONLY', 'READWRITE', name='permission'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'instance_id', name='uq_dept_instance')
    )
    with op.batch_alter_table('department_instance_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_instance_bindings_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_instance_bindings_instance_id'), ['instance_id'], unique=False)

    op.create_table('user_instance_bindings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('db_account_id', sa.String(length=36), nullable=True),
    sa.Column('permission', sa.Enum('READONLY', 'READWRITE', name='permission'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['db_account_id'], ['db_accounts.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'instance_id', name='uq_user_instance')
    )
    with op.batch_alter_table('user_instance_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_instance_bindings_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_instance_bindings_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_instance_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_instance_bindings_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_instance_bindings_instance_id'))

    op.drop_table('user_instance_bindings')
    with op.batch_alter_table('department_instance_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_instance_bindings_instance_id'))
        batch_op.drop_index(batch_op.f('ix_department_instance_bindings_department_id'))

    op.drop_table('department_instance_bindings')
    with op.batch_alter_table('db_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_db_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_db_accounts_instance_id'))

    op.drop_table('db_accounts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_instance_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('user_departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_departments_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_departments_department_id'))

    op.drop_table('user_departments')
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instances_cluster_id'))

    op.drop_table('instances')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_external_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('departments')
    # ### end Alembic commands ###
