"""drop redundant index user_refresh_tokens.token_hash

Revision ID: 23682b6c9be4
Revises: 6f2db1f2b983
Create Date: 2026-06-17 21:22:43.073043

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '23682b6c9be4'
down_revision: Union[str, Sequence[str], None] = '6f2db1f2b983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_refresh_tokens_token_hash'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_refresh_tokens_token_hash'), ['token_hash'], unique=False)

    # ### end Alembic commands ###
