"""add users.default_instance_id

Revision ID: 34c7c621e733
Revises: 03f4db502e26
Create Date: 2026-06-10 12:11:28.932969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c7c621e733'
down_revision: Union[str, Sequence[str], None] = '03f4db502e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_instance_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            'fk_users_default_instance_id', 'instances',
            ['default_instance_id'], ['id'], ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_default_instance_id', type_='foreignkey')
        batch_op.drop_column('default_instance_id')

    # ### end Alembic commands ###
