"""add user_refresh_tokens

Revision ID: 3cd36ba362d3
Revises: 60bf33cf8745
Create Date: 2026-06-17 19:01:20.354168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd36ba362d3'
down_revision: Union[str, Sequence[str], None] = '60bf33cf8745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_family', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_refresh_tokens_token_family'), ['token_family'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_refresh_tokens_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_refresh_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_user_refresh_tokens_token_family'))

    op.drop_table('user_refresh_tokens')
    # ### end Alembic commands ###
