"""add_audit_traceability_fields

Revision ID: 584da171771a
Revises: 23682b6c9be4
Create Date: 2026-06-19 19:12:09.204644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584da171771a'
down_revision: Union[str, Sequence[str], None] = '23682b6c9be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sql_type', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('user_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instance_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('db_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('db_name')
        batch_op.drop_column('instance_name')
        batch_op.drop_column('user_name')
        batch_op.drop_column('sql_type')

    # ### end Alembic commands ###
