"""add multitenant provisioning

Revision ID: 60bf33cf8745
Revises: 36af7dd2992e
Create Date: 2026-06-12 11:06:24.350831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60bf33cf8745'
down_revision: Union[str, Sequence[str], None] = '36af7dd2992e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_name', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('provisioning_step', sa.Enum('PENDING', 'RESOURCE_CONFIG', 'TENANT', 'USER', 'DATABASE', 'GRANT', name='tenantprovisioningstep'), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PERSONAL', 'SHARED', 'MULTITENANT', name='instancetype'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('ACTIVE', 'STOPPED', 'CREATING', 'POOLED', 'POOL_CREATING', 'FAILED', name='instancestatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVE', 'STOPPED', 'CREATING', 'POOLED', 'POOL_CREATING', 'FAILED', name='instancestatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.Enum('PERSONAL', 'SHARED', 'MULTITENANT', name='instancetype'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    with op.batch_alter_table('db_accounts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('provisioning_step')
        batch_op.drop_column('tenant_name')

    # ### end Alembic commands ###
