"""unique constraint on user_refresh_tokens.token_hash

Revision ID: 6f2db1f2b983
Revises: 3cd36ba362d3
Create Date: 2026-06-17 19:11:46.960870

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6f2db1f2b983'
down_revision: Union[str, Sequence[str], None] = '3cd36ba362d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_refresh_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_refresh_tokens_token_hash', ['token_hash'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_refresh_tokens_token_hash', type_='unique')

    # ### end Alembic commands ###
