"""add idp_authorize_url to oauth_pending_auths

Revision ID: 81ce053ed593
Revises: b3b20147bcc4
Create Date: 2026-06-11 15:24:11.963293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ce053ed593'
down_revision: Union[str, Sequence[str], None] = 'b3b20147bcc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_pending_auths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idp_authorize_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_pending_auths', schema=None) as batch_op:
        batch_op.drop_column('idp_authorize_url')

    # ### end Alembic commands ###
