"""add oauth tables

Revision ID: b3b20147bcc4
Revises: 34c7c621e733
Create Date: 2026-06-10 22:52:13.410894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b20147bcc4'
down_revision: Union[str, Sequence[str], None] = '34c7c621e733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_denied_jtis',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('oauth_pending_auths',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('code_challenge', sa.String(length=128), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=10), nullable=False),
    sa.Column('resource', sa.Text(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('idp_state', sa.String(length=36), nullable=True),
    sa.Column('idp_code_verifier_enc', sa.Text(), nullable=True),
    sa.Column('idp_nonce', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('oauth_registered_clients',
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret_enc', sa.Text(), nullable=True),
    sa.Column('client_id_issued_at', sa.Integer(), nullable=True),
    sa.Column('client_secret_expires_at', sa.Integer(), nullable=True),
    sa.Column('redirect_uris', sa.Text(), nullable=False),
    sa.Column('grant_types', sa.Text(), nullable=False),
    sa.Column('response_types', sa.Text(), nullable=False),
    sa.Column('token_endpoint_auth_method', sa.String(length=50), nullable=True),
    sa.Column('scope', sa.String(length=500), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('oauth_authorization_codes',
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('redirect_uri_provided_explicitly', sa.Boolean(), nullable=False),
    sa.Column('code_challenge', sa.String(length=128), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=10), nullable=False),
    sa.Column('resource', sa.Text(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code_hash')
    )
    with op.batch_alter_table('oauth_authorization_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_authorization_codes_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_authorization_codes_user_id'), ['user_id'], unique=False)

    op.create_table('oauth_refresh_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code_id', sa.String(length=64), nullable=True),
    sa.Column('token_family', sa.String(length=36), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('resource', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('oauth_refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_refresh_tokens_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_refresh_tokens_code_id'), ['code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_refresh_tokens_token_family'), ['token_family'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('user_external_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('identity_provider', sa.String(length=100), nullable=False),
    sa.Column('external_subject', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_provider', 'external_subject', name='uq_idp_subject')
    )
    with op.batch_alter_table('user_external_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_external_identities_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_external_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_external_identities_user_id'))

    op.drop_table('user_external_identities')
    with op.batch_alter_table('oauth_refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_refresh_tokens_token_family'))
        batch_op.drop_index(batch_op.f('ix_oauth_refresh_tokens_code_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_refresh_tokens_client_id'))

    op.drop_table('oauth_refresh_tokens')
    with op.batch_alter_table('oauth_authorization_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_authorization_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_authorization_codes_client_id'))

    op.drop_table('oauth_authorization_codes')
    op.drop_table('oauth_registered_clients')
    op.drop_table('oauth_pending_auths')
    op.drop_table('oauth_denied_jtis')
    # ### end Alembic commands ###
