apiVersion: v2
name: polardb-agentic-server
description: Alibaba Cloud PolarDB Tool Agentic Server
type: application
version: 0.0.1
appVersion: "0.0.1"
home: https://github.com/aliyun/alibabacloud-polardb-tool-agentic-server
sources:
  - https://github.com/aliyun/alibabacloud-polardb-tool-agentic-server
